
services:
  homework1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    ports:
      - 8000:8000

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672