basePath: /
host: 127.0.0.1:8080
info:
  contact: {}
  description: this is my second homework
  title: Homework1
  version: "1.0"
paths:
  /task:
    post:
      description: Creates a task
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Post task
      tags:
      - Task
  /task/{task_id}:
    get:
      description: Get the status of the ongoing task
      parameters:
      - description: ID of the task
        in: path
        name: task_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Get Status
      tags:
      - Task
swagger: "2.0"
